### ISSUE TITLE
/sites/{hostname}:/{relative-path} missing in OpenAPI description

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-metadata#404]
Path
`/sites/{hostname}:/{relative-path}` is missing in OpenAPI description.

Docs: https://learn.microsoft.com/en-us/graph/api/site-getbypath?view=graph-rest-1.0

Raptor report:
Original HTTP Snippet:
GET /v1.0/sites/{hostname}:/{relative-path} HTTP/1.1
Host: graph.microsoft.com

Exception while processing /home/vsts/work/1/a/Snippets/get-site-by-hostname-and-path-v1-httpSnippet.
Path segment '{relative-path}' not found in path
at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod) at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod)
at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments, HttpMethod httpMethod)
at CodeSnippetsReflection.OpenAPI.SnippetModel..ctor(HttpRequestMessage requestPayload, String serviceRootUrl, OpenApiSnippetMetadata openApiSnippetMetadata) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 39
at CodeSnippetsReflection.OpenAPI.OpenApiSnippetsGenerator.ProcessPayloadRequest(HttpRequestMessage requestPayload, String language) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs:line 57
at CodeSnippetsReflection.App.Program.ProcessFile(ISnippetsGenerator generator, String language, String file) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.App/Program.cs:line 156

Stack trace:

at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

**Comment by isvargasmsft** [comment]
Originally reported here: https://github.com/microsoft/OpenAPI.NET.OData/issues/406

**Comment by irvinesunday** [comment]
Unfortunately, there's no OData to OpenAPI convention for generating the path: `/sites/{hostname}:/{relative-path}`

From the docs:
> In addition to retrieving a [site by ID](https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0) you can retrieve a site based on server-relative URL path.

> Site collection hostname (contoso.sharepoint.com)
> Site path, relative to server hostname.

The _hostname_ and _relative-path_ do not form part of any of the navigation properties within the entity type `site` that the conversion lib would have generated.
