### ISSUE TITLE
Path segment 'comments' not found in path

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-metadata#416]
Path:
`POST /v1.0/security/alerts_v2/{ID}/comments` not found

Complete report:
Original HTTP Snippet:
POST /v1.0/security/alerts_v2/da637865765418431569_-773071023/comments HTTP/1.1
Content-Type: application/json
Host: graph.microsoft.com
Content-Length: 99

{
"@odata.type": "microsoft.graph.security.alertComment",
"comment": "Demo for docs"
}

Exception while processing /home/vsts/work/1/a/Snippets/alert-v2-addcomment-v1-httpSnippet.
Path segment 'comments' not found in path
at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod)    at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod)
at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod)    at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable1 pathSegments, HttpMethod httpMethod)
at CodeSnippetsReflection.OpenAPI.SnippetModel..ctor(HttpRequestMessage requestPayload, String serviceRootUrl, OpenApiSnippetMetadata openApiSnippetMetadata) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 39
at CodeSnippetsReflection.OpenAPI.OpenApiSnippetsGenerator.ProcessPayloadRequest(HttpRequestMessage requestPayload, String language) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs:line 68
at CodeSnippetsReflection.App.Program.ProcessFile(ISnippetsGenerator generator, String language, String file) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.App/Program.cs:line 156

Stack trace
   at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
   at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

1)    at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
   at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

Docs: https://learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&tabs=http

**Comment by irvinesunday** [comment]
To enable this, the below annotation will need to be added:

```XML
<Annotations Target="microsoft.graph.security.alert/comments">
  <Annotation Term="Org.OData.Capabilities.V1.InsertRestrictions">
    <Record>
      <PropertyValue Property="Insertable" Bool="true" />
    </Record>
  </Annotation>        
</Annotations>
```

**Comment by irvinesunday** [comment]
Resolved by https://github.com/microsoftgraph/msgraph-metadata/pull/422
